FROM mongo:4.4

#exponer puerto por defecto de mongo
EXPOSE 27017

#copiar los ficheros y scripts necesarios
RUN mkdir mongo 
WORKDIR /mongo
COPY import_distances.sh import_distances.sh
RUN chmod +x import_distances.sh
RUN mkdir data
COPY origin_dest_distances.jsonl data/origin_dest_distances.jsonl 

# copiar el script de inicializacion de mongo y ejecutarlo
COPY mongo.sh mongo.sh
RUN chmod +x mongo.sh
CMD ["./mongo.sh"]

